# Generated by Django 5.0.3 on 2024-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercust',
            name='emailaddress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usercust',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usercust',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usercust',
            name='addresss',
            field=models.TextField(),
        ),
    ]
