# Generated by Django 5.0.3 on 2024-04-24 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_usercust_emailaddress_usercust_fname_usercust_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credict_cardno', models.PositiveIntegerField()),
                ('exp', models.DateField()),
                ('ccv', models.CharField(max_length=3)),
                ('amount', models.PositiveIntegerField()),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.usercust')),
            ],
        ),
    ]
