# Generated by Django 5.0.3 on 2024-05-06 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('isapproved', models.BooleanField(default=False)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.usercust')),
            ],
        ),
    ]
