# Generated by Django 5.0.3 on 2024-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_adoptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionFormView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criminal_history', models.BooleanField()),
                ('id_proof', models.FileField(upload_to='images/')),
                ('additional_comments', models.TextField(blank=True, null=True)),
                ('isrejected', models.BooleanField(default=False)),
            ],
        ),
    ]
