# Generated by Django 5.0.3 on 2024-05-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0005_adoptionformview'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionformview',
            name='personaldetails',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ca.usercust'),
        ),
        migrations.AlterField(
            model_name='adoptionformview',
            name='additional_comments',
            field=models.TextField(),
        ),
    ]
