# Generated by Django 5.0.3 on 2024-05-06 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0006_adoptionformview_personaldetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionformview',
            old_name='personaldetails',
            new_name='personal_details',
        ),
    ]
