# Generated by Django 5.0.3 on 2024-05-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0007_rename_personaldetails_adoptionformview_personal_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionformview',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
