# Generated by Django 5.0.3 on 2024-05-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0008_adoptionformview_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionformview',
            old_name='isrejected',
            new_name='isaccepted',
        ),
    ]
