# Generated by Django 5.0.3 on 2024-05-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0009_rename_isrejected_adoptionformview_isaccepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('since', models.PositiveIntegerField()),
            ],
        ),
    ]
