# Generated by Django 5.0.3 on 2024-05-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0010_childdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='exit', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childdetails',
            name='age',
            field=models.CharField(max_length=50),
        ),
    ]
