# Generated by Django 5.0.3 on 2024-05-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0011_childdetails_gender_alter_childdetails_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ConformChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isapproved', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.childdetails')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ca.usercust')),
            ],
        ),
    ]
