# Generated by Django 5.0.3 on 2024-05-15 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0012_alter_childdetails_gender_conformchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(choices=[('medical', 'Medical'), ('clothings', 'Clothings'), ('education', 'Education'), ('sports', 'Sports'), ('food and nutrition', 'Food and Nutrition')], max_length=20, null=True)),
                ('credict_cardno', models.PositiveIntegerField()),
                ('exp', models.DateField()),
                ('ccv', models.CharField(max_length=3)),
                ('budget', models.PositiveIntegerField()),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ca.usercust')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.childdetails')),
            ],
        ),
    ]
