# Generated by Django 5.0.3 on 2024-05-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0013_sponsertable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsertable',
            old_name='credict_cardno',
            new_name='credit_cardno',
        ),
        migrations.AlterField(
            model_name='sponsertable',
            name='sponsor_type',
            field=models.CharField(choices=[('medical', 'Medical'), ('clothings', 'Clothings'), ('education', 'Education'), ('sports', 'Sports'), ('food_and_nutrition', 'Food and Nutrition')], max_length=20, null=True),
        ),
    ]
