# Generated by Django 5.0.3 on 2024-05-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0014_rename_credict_cardno_sponsertable_credit_cardno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsertable',
            old_name='User',
            new_name='user',
        ),
    ]
